### ISSUE TITLE
ValueError: Invalid activation function: leakyrelu

### ISSUE THREAD

**Issue by ClinuxMDL** [Shen-Lab/gcWGAN#1]
Hi developers,

An invalid error occurs:
> python Nov_SeqGenerator_Filter.py ./DeepSF_modified/DeepSF_model_weight_more_folds/model-train-weight-DLS2F.h5 ALL 100 test_generated_file_index test_job_index M_DeepSF

Using TensorFlow backend.
./DeepSF_modified/DeepSF_model_weight_more_folds/model-train-weight-DLS2F.h5
Modified: True
Original: False
Uppercase local vars:
	BATCH_SIZE: 200
	DATA_DIR: ../Data/Datasets/Final_Data/
	DIM: 512
	GEN_NUM: 100
	JOB_INDEX: test_job_index
	K: <module 'keras.backend' from '/usr/local/lib/python3.6/dist-packages/keras/backend/__init__.py'>
	KIND: ALL
	LAMBDA: 10
	MAX_LEN: 160
	MAX_N_EXAMPLES: 50000
	MIN_LEN: 60
	SEQ_LEN: 160
	THRESHOLD: 0.21
	TOP_NUM: 10
loading dataset...
loaded 20125 lines in dataset
Data loading successfully!
WARNING: Logging before flag parsing goes to stderr.
W0214 17:46:15.818645 140365499090752 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:321: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "Nov_SeqGenerator_Filter_r1py3.py", line 143, in <module>
    M_DLS2F_CNN = model_from_json(M_loaded_model_json, custom_objects={'K_max_pooling1d': Oracle_Filters.K_max_pooling1d})
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 213, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/layer_utils.py", line 40, in layer_from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2582, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2560, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/layer_utils.py", line 42, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 1025, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 106, in __init__
    self.activation = activations.get(activation)
  File "/usr/local/lib/python3.6/dist-packages/keras/activations.py", line 55, in get
    return get_from_module(identifier, globals(), 'activation function')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 125, in get_from_module
    str(identifier))
ValueError: Invalid activation function: leakyrelu

**Comment by Shaowen1994** [comment]
> Hi developers,
> 
> An invalid error occurs:
> 
> > python Nov_SeqGenerator_Filter.py ./DeepSF_modified/DeepSF_model_weight_more_folds/model-train-weight-DLS2F.h5 ALL 100 test_generated_file_index test_job_index M_DeepSF
> 
> Using TensorFlow backend.
> ./DeepSF_modified/DeepSF_model_weight_more_folds/model-train-weight-DLS2F.h5
> Modified: True
> Original: False
> Uppercase local vars:
> BATCH_SIZE: 200
> DATA_DIR: ../Data/Datasets/Final_Data/
> DIM: 512
> GEN_NUM: 100
> JOB_INDEX: test_job_index
> K: <module 'keras.backend' from '/usr/local/lib/python3.6/dist-packages/keras/backend/**init**.py'>
> KIND: ALL
> LAMBDA: 10
> MAX_LEN: 160
> MAX_N_EXAMPLES: 50000
> MIN_LEN: 60
> SEQ_LEN: 160
> THRESHOLD: 0.21
> TOP_NUM: 10
> loading dataset...
> loaded 20125 lines in dataset
> Data loading successfully!
> WARNING: Logging before flag parsing goes to stderr.
> W0214 17:46:15.818645 140365499090752 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:321: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> Traceback (most recent call last):
> File "Nov_SeqGenerator_Filter_r1py3.py", line 143, in
> M_DLS2F_CNN = model_from_json(M_loaded_model_json, custom_objects={'K_max_pooling1d': Oracle_Filters.K_max_pooling1d})
> File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 213, in model_from_json
> return layer_from_config(config, custom_objects=custom_objects)
> File "/usr/local/lib/python3.6/dist-packages/keras/utils/layer_utils.py", line 40, in layer_from_config
> custom_objects=custom_objects)
> File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2582, in from_config
> process_layer(layer_data)
> File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2560, in process_layer
> custom_objects=custom_objects)
> File "/usr/local/lib/python3.6/dist-packages/keras/utils/layer_utils.py", line 42, in layer_from_config
> return layer_class.from_config(config['config'])
> File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 1025, in from_config
> return cls(**config)
> File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 106, in **init**
> self.activation = activations.get(activation)
> File "/usr/local/lib/python3.6/dist-packages/keras/activations.py", line 55, in get
> return get_from_module(identifier, globals(), 'activation function')
> File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 125, in get_from_module
> str(identifier))
> ValueError: Invalid activation function: leakyrelu


Dear user,

Thank you for your feedback!

This error results from that "leakyrelu" was not a built-in function of original keras, and we directly added it ourselves. To solve it, you can add the attached function in the file **"\<path where keras was installed>/keras/activations.py"**. We have also updated the **Pre-requisite** in our **Readme** file accordingly. 
```
def leakyrelu(x, alpha=0.1, max_value=None):
    return K.relu(x, alpha=alpha, max_value=max_value)
```

Best,
Shaowen

**Comment by ClinuxMDL** [comment]
It works for me.
